#!/bin/bash

SECONDS=0
start=0
#echo > log.txt "$SECONDS"
[[ -e log.txt ]] || echo > log.txt "$SECONDS"

SPOILER="I watched Avengers: Endgame."

while ((1))
do
	if [[ $start != $SECONDS ]]
	then
		sleep 1
		echo "$SECONDS"
		echo >> log.txt "$SECONDS"
		start=$SECONDS
		
		RAND=$RANDOM
		if [[ $((RAND%3)) -eq 0 ]]
		then
			echo $SPOILER
			echo >> log.txt "$SPOILER"
			continue
		fi
	fi
done

